{% set name = "yagmail" %}
{% set version = "0.13.241" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf66fdfe786be05d10aa9d39df61cddea37130478d3cac70a0d0ab39da559b48

build:
  number: 0
  noarch: python
  entry_points:
    - yagmail = yagmail.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - premailer
    - python
  run:
    - python

test:
  imports:
    - yagmail
  commands:
    - yagmail --help

about:
  home: https://github.com/kootenpv/yagmail
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Yet Another GMAIL client

extra:
  recipe-maintainers:
    - setu4993
