{% set name = "yagmail" %}
{% set version = "0.14.244" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4b2c5546d801867df5835711726e927417bbc781d5706b564745908a03aa360

build:
  number: 0
  noarch: python
  entry_points:
    - yagmail = yagmail.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - premailer
    - python
  run:
    - python

test:
  imports:
    - yagmail
  commands:
    - yagmail --help

about:
  home: https://github.com/kootenpv/yagmail
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Yet Another GMAIL client

extra:
  recipe-maintainers:
    - setu4993
